name: Call PR Title

on:
  pull_request:
    branches: 
      - main
      - f/call_pr_title
  workflow_dispatch:

jobs:
  update_pr_title:
    uses: lightzane/try-ghactions-sharedwf/.github/workflows/pr_title.yaml@main
