name: Call PR Title

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Run shared workflow
        uses: lightzane/try-ghactions-sharedwf/.github/workflows/pr_title.yaml@main
