name: Call PR Title

on:
  pull_request:
    branches: 
      - main
      - f/call_pr_title
  workflow_dispatch:

env: 
  TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Call other workflow
        uses: lightzane/try-ghactions-sharedwf/.github/workflows/pr_title.yaml@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}
