name: Copy Template PR Title

on: push

env:
  token: ${{ secrets.GH_TOKEN }}

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout target code
        uses: actions/checkout@v4
        with:
          repository: lightzane/try-ghactions-output
          ref: main
          path: target
          token: ${{ env.token }} # defaults to ${{ github.token }}
          # token must have the following scopes:
          #  - read:discussion
          #  - read:org
          #  - repo
          #  - workflow

      # Single File
      # - name: Copy a template
      #   run: |
      #     FILE=call_pr_title.yaml
      #     DESTINATION=.github/workflows
          
      #     echo "FILE=$FILE" >> $GITHUB_ENV
      #     echo "DESTINATION=$DESTINATION" >> $GITHUB_ENV
          
      #     cp source/templates/$FILE target/$DESTINATION

      # Entire directory
      - name: Copy template directory
        run: |
          DESTINATION=.github/workflows          
          
          # Move all files along with the folder
          # cp -r source/templates target/$DESTINATION

          # Move ONLY all files inside the folder
          cp -r source/templates/* target/$DESTINATION

      - name: Check-in target repository
        working-directory: target # See Line 22
        run: |
          # Check if there are any changes (-n = means non-zero length; -z = means zero-length)
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "🤖 WF_Copied_WFTemplates"
            git push
          else
            echo "No changes to commit."
          fi
        
        
