name: Shared Workflows

on:
  workflow_call:
    inputs:
      example_input:
        description: An example input
        required: true
        type: string

jobs:
  shared-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script from DEV branch of shared workflow
        run: |
          echo "(DEV) This is an example running on shared workflow"
          echo "(DEV) Input is: ${{ inputs.example_input }}"

      - name: Project list
        run: ls
