name: Shared Workflows

on:
  workflow_call:
    inputs:
      example_input:
        description: An example input
        required: true
        type: string
        default: Example input for shared workflow

jobs:
  shared-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script from MAIN branch of shared workflow
        run: |
          echo "This is an example running on shared workflow"
          echo "Input is: ${{ inputs.example_input }}"
